### ISSUE TITLE
OpenGraph fetch should use timeout for network calls

### ISSUE THREAD

**Issue by jaywink** [jaywink/socialhome#195]
Seems we're having some RQ jobs timeouting due to OpenGraph fetch taking too long. Investigate why and add an aggressive timeout.

    Traceback (most recent call last):
      File "/xxxxxxxxxxxxxxxxxx/socialhome/socialhome/content/signals.py", line 44, in fetch_preview
        fetch_content_preview(content)
      File "/xxxxxxxxxxxxxxxxxx/socialhome/socialhome/content/previews.py", line 35, in fetch_content_preview
        fetch_og_preview(content, urls)
      File "/xxxxxxxxxxxxxxxxxx/socialhome/socialhome/content/previews.py", line 49, in fetch_og_preview
        og = OpenGraph(url=url)
      File "/xxxxxxxxxxxxxxxxxx/venv/lib/python3.4/site-packages/opengraph/opengraph.py", line 17, in __init__
        content = html or self._fetch(url)
      File "/xxxxxxxxxxxxxxxxxx/venv/lib/python3.4/site-packages/opengraph/opengraph.py", line 41, in _fetch
        response = requests.get(url, headers=headers)
      File "/xxxxxxxxxxxxxxxxxx/venv/lib/python3.4/site-packages/requests/api.py", line 72, in get
        return request('get', url, params=params, **kwargs)
    ........
    rq.timeouts.JobTimeoutException: Job exceeded maximum timeout value (360 seconds)

**Comment by jaywink** [comment]
Closed via #323
