### ISSUE TITLE
Replace Celery with RQ

### ISSUE THREAD

**Issue by jaywink** [jaywink/socialhome#88]
Celery has become a nuisance. RQ would be an easier to maintain solution.

Also maybe consider just using Channels workers. How would that work?

**Comment by jaywink** [comment]
Outward posting seems to be broken since updating to Celery 4 ... a test case for the job actually being pushed to RQ job would be good to avoid this kind of thing when RQ replaces Celery.

    Traceback (most recent call last):
      File "./socialhome/content/signals.py", line 36, in federate_content
        send_content.delay(content)
      File "/home/jasonrobinson/venv/lib/python3.4/site-packages/celery/app/task.py", line 412, in delay
        return self.apply_async(args, kwargs)
      File "/home/jasonrobinson/venv/lib/python3.4/site-packages/celery/app/task.py", line 535, in apply_async
        **options
      File "/home/jasonrobinson/venv/lib/python3.4/site-packages/celery/app/base.py", line 737, in send_task
        amqp.send_task_message(P, name, message, **options)
        .......
      File "/home/jasonrobinson/venv/lib/python3.4/site-packages/kombu/utils/json.py", line 62, in default
        return super(JSONEncoder, self).default(o)
      File "/usr/lib/python3.4/json/encoder.py", line 173, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    kombu.exceptions.EncodeError: <Content: ![](https://jasonrobinson.me/media/markdownx/f846e867-b685-4b5e-8909-ba4e685e4cc9.jpg) (dcd52496-c954-4c38-ac3f-5d816abf4718)> is not JSON serializable
